//! "Send to" entries: `%APPDATA%\Microsoft\Windows\SendTo\<label>.cmd`.
//!
//! Send To hands *all* selected files to the target in a single launch (`%*`, each path
//! quoted by Explorer), with no per-verb item cap other than the 32 767-character command line.
//! That makes it the simple fallback for huge selections, on Windows 10 and 11 alike. We write
//! a `.cmd` rather than a `.lnk`: it is plain text (testable, no COM), and Explorer accepts it.
//! Trade-off: `cmd.exe` shows a console window briefly.

use std::path::PathBuf;

use crate::context::{Context, Platform};
use crate::error::{Result, ShellError};
use crate::fsutil::{MARKER, ManagedFile, files_current, install_files, uninstall_files};
use crate::integration::{Description, Detection, InstallOutcome, Integration, UninstallOutcome};
use crate::quote::win_batch_quote;

/// Send To folder integration.
#[derive(Debug, Clone, Copy, Default)]
pub struct SendTo;

impl SendTo {
    /// Creates the integration.
    pub fn new() -> Self {
        Self
    }

    fn dir(ctx: &Context) -> Result<PathBuf> {
        let appdata = ctx
            .appdata
            .as_ref()
            .ok_or_else(|| ShellError::Unavailable("%APPDATA% is not set".into()))?;
        Ok(appdata.join("Microsoft").join("Windows").join("SendTo"))
    }

    fn files(ctx: &Context) -> Result<Vec<ManagedFile>> {
        let dir = Self::dir(ctx)?;
        ctx.actions
            .iter()
            .filter(|a| a.multi_select)
            .map(|a| {
                if a.label.contains(['<', '>', ':', '"', '/', '\\', '|', '?', '*']) {
                    return Err(ShellError::InvalidAction {
                        id: a.id.clone(),
                        reason: "label is not a valid Windows file name".into(),
                    });
                }
                Ok(ManagedFile::new(
                    dir.join(format!("{}.cmd", a.label)),
                    cmd_source(ctx, a)?,
                    0o644,
                ))
            })
            .collect()
    }
}

/// The batch file for one action (CRLF line endings, UTF-8, no BOM).
pub(crate) fn cmd_source(ctx: &Context, a: &crate::action::Action) -> Result<String> {
    let exe_raw = ctx.exe_str()?;
    let exe = win_batch_quote(exe_raw)?;
    let mut lines = vec!["@echo off".to_owned()];
    if !exe_raw.is_ascii() {
        // The batch parser reads the file in the OEM code page; switch so the path survives.
        lines.push("chcp 65001 >nul".to_owned());
    }
    lines.push(format!(
        "rem {MARKER}: generated by ssx. Edits are overwritten; delete via ssx or remove this file."
    ));
    let mut cmd = exe;
    for arg in &a.exec_args {
        if arg.contains(['"', '%', '^', '&', '|', '<', '>', ' ']) {
            return Err(ShellError::InvalidAction {
                id: a.id.clone(),
                reason: format!("argument {arg:?} cannot be used in a batch file"),
            });
        }
        cmd.push(' ');
        cmd.push_str(arg);
    }
    cmd.push_str(" -- %*");
    lines.push(cmd);
    let mut out = lines.join("\r\n");
    out.push_str("\r\n");
    Ok(out)
}

impl Integration for SendTo {
    fn id(&self) -> &'static str {
        "windows-sendto"
    }

    fn name(&self) -> &'static str {
        "Windows \"Send to\" menu"
    }

    fn platform(&self) -> Platform {
        Platform::Windows
    }

    fn detect(&self, ctx: &Context) -> Detection {
        match &ctx.appdata {
            Some(_) => Detection::found("%APPDATA% is set"),
            None => Detection::missing("%APPDATA% is not set"),
        }
    }

    fn install(&self, ctx: &Context) -> Result<InstallOutcome> {
        install_files(&Self::files(ctx)?)
    }

    fn uninstall(&self, ctx: &Context) -> Result<UninstallOutcome> {
        uninstall_files(&Self::files(ctx)?, ctx)
    }

    fn is_installed(&self, ctx: &Context) -> Result<bool> {
        files_current(&Self::files(ctx)?)
    }

    fn describe(&self, ctx: &Context) -> Description {
        let paths: Vec<PathBuf> =
            Self::files(ctx).map(|f| f.into_iter().map(|f| f.path).collect()).unwrap_or_default();
        Description::paths(
            "windows-sendto",
            "\"Send to\" entries (all selected files in one launch)",
            &paths,
        )
        .note("right-click > Send to > Upload with ssx; best for very large selections")
        .note("uses a .cmd file, so a console window flashes briefly")
    }
}
