//! Finder Quick Actions: Automator workflow bundles in `~/Library/Services`.
//!
//! A Quick Action is a `<name>.workflow` bundle with two files that we generate as text:
//! `Contents/Info.plist` (declares the Services menu entry: `NSServices`, `NSSendFileTypes`)
//! and `Contents/document.wflow` (the Automator workflow: a single "Run Shell Script" action
//! receiving the selected files **as arguments**, so `"$@"` is the exact list of POSIX paths).
//! Finder shows them under right-click > Quick Actions (and Services).
//!
//! **Not verified on a real Mac**: the plist structure follows what Automator writes for a
//! "Quick Action / files or folders in Finder" workflow and is validated here only for
//! well-formedness, golden output and script behaviour. After installing, `pbs -update` asks
//! the Services daemon to rescan; the user may still have to enable the entries in
//! System Settings > Keyboard > Keyboard Shortcuts > Services > Files and Folders (or
//! System Settings > Extensions > Finder).

use std::path::PathBuf;

use crate::action::{Action, FilterKind};
use crate::context::{Context, Platform};
use crate::error::{Result, ShellError};
use crate::fsutil::{MARKER, ManagedFile, files_current, install_files, uninstall_files};
use crate::integration::{Description, Detection, InstallOutcome, Integration, UninstallOutcome};
use crate::quote::{sh_word, xml_escape};
use crate::windows::manifest::guid_for;

const PBS: &str = "/System/Library/CoreServices/pbs";

/// Finder Quick Actions integration.
#[derive(Debug, Clone, Copy, Default)]
pub struct QuickActions;

impl QuickActions {
    /// Creates the integration.
    pub fn new() -> Self {
        Self
    }

    fn bundle(ctx: &Context, a: &Action) -> PathBuf {
        ctx.home.join("Library").join("Services").join(format!("{}.workflow", a.label))
    }

    fn files(ctx: &Context) -> Result<Vec<ManagedFile>> {
        let mut files = Vec::new();
        for a in &ctx.actions {
            if a.label.contains(['/', ':']) || a.label.starts_with('.') {
                return Err(ShellError::InvalidAction {
                    id: a.id.clone(),
                    reason: "Quick Action bundles are named after the label, which must not contain '/' or ':' or start with '.'".into(),
                });
            }
            let contents = Self::bundle(ctx, a).join("Contents");
            files.push(ManagedFile::new(contents.join("Info.plist"), info_plist(a), 0o644));
            files.push(ManagedFile::new(
                contents.join("document.wflow"),
                document_wflow(ctx, a)?,
                0o644,
            ));
        }
        Ok(files)
    }

    fn refresh(ctx: &Context) {
        if let Err(e) = ctx.runner.run(PBS, &["-update".to_owned()]) {
            tracing::debug!(error = %e, "pbs -update not run");
        }
    }
}

impl Integration for QuickActions {
    fn id(&self) -> &'static str {
        "macos-quick-actions"
    }

    fn name(&self) -> &'static str {
        "Finder Quick Actions"
    }

    fn platform(&self) -> Platform {
        Platform::MacOs
    }

    fn detect(&self, _ctx: &Context) -> Detection {
        Detection::found("Finder")
    }

    fn install(&self, ctx: &Context) -> Result<InstallOutcome> {
        let outcome = install_files(&Self::files(ctx)?)?;
        if outcome != InstallOutcome::AlreadyPresent {
            Self::refresh(ctx);
        }
        Ok(outcome)
    }

    fn uninstall(&self, ctx: &Context) -> Result<UninstallOutcome> {
        let outcome = uninstall_files(&Self::files(ctx)?, ctx)?;
        if outcome == UninstallOutcome::Removed {
            Self::refresh(ctx);
        }
        Ok(outcome)
    }

    fn is_installed(&self, ctx: &Context) -> Result<bool> {
        files_current(&Self::files(ctx)?)
    }

    fn describe(&self, ctx: &Context) -> Description {
        let paths: Vec<PathBuf> = ctx.actions.iter().map(|a| Self::bundle(ctx, a)).collect();
        Description::paths("macos-quick-actions", "Finder Quick Actions (right-click > Quick Actions)", &paths)
            .note("runs `pbs -update` so Finder notices the new services")
            .note("if an entry is missing, enable it under System Settings > Keyboard > Keyboard Shortcuts > Services > Files and Folders")
    }
}

fn uti_for(a: &Action) -> &'static str {
    match a.filter.kind {
        FilterKind::Images => "public.image",
        FilterKind::Videos => "public.movie",
        FilterKind::Any | FilterKind::Custom => "public.item",
    }
}

const PLIST_HEAD: &str = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n";

/// `Contents/Info.plist` for one action.
pub(crate) fn info_plist(a: &Action) -> String {
    format!(
        "{PLIST_HEAD}<!-- {MARKER}: generated by ssx. Edits are overwritten; remove via ssx or delete this bundle. -->\n\
<plist version=\"1.0\">\n\
<dict>\n\
\t<key>NSServices</key>\n\
\t<array>\n\
\t\t<dict>\n\
\t\t\t<key>NSBackgroundColorName</key>\n\
\t\t\t<string>background</string>\n\
\t\t\t<key>NSIconName</key>\n\
\t\t\t<string>NSActionTemplate</string>\n\
\t\t\t<key>NSMenuItem</key>\n\
\t\t\t<dict>\n\
\t\t\t\t<key>default</key>\n\
\t\t\t\t<string>{label}</string>\n\
\t\t\t</dict>\n\
\t\t\t<key>NSMessage</key>\n\
\t\t\t<string>runWorkflowAsService</string>\n\
\t\t\t<key>NSRequiredContext</key>\n\
\t\t\t<dict>\n\
\t\t\t\t<key>NSApplicationIdentifier</key>\n\
\t\t\t\t<string>com.apple.finder</string>\n\
\t\t\t</dict>\n\
\t\t\t<key>NSSendFileTypes</key>\n\
\t\t\t<array>\n\
\t\t\t\t<string>{uti}</string>\n\
\t\t\t</array>\n\
\t\t</dict>\n\
\t</array>\n\
</dict>\n\
</plist>\n",
        label = xml_escape(&a.label),
        uti = uti_for(a),
    )
}

/// The shell script Automator runs; the selected files arrive as `"$@"`.
pub(crate) fn shell_script(ctx: &Context, a: &Action) -> Result<String> {
    let exe = sh_word(ctx.exe_str()?);
    let args: Vec<String> = a.exec_args.iter().map(|x| sh_word(x)).collect();
    let args = args.join(" ");
    Ok(if a.multi_select {
        format!("exec {exe} {args} -- \"$@\"\n")
    } else {
        format!("for f in \"$@\"; do\n    {exe} {args} -- \"$f\"\ndone\n")
    })
}

/// `Contents/document.wflow` for one action.
pub(crate) fn document_wflow(ctx: &Context, a: &Action) -> Result<String> {
    let script = xml_escape(&shell_script(ctx, a)?);
    let action_uuid =
        guid_for(&format!("ssx-shell:wflow:action:{}", a.id)).trim_matches(['{', '}']).to_owned();
    let input_uuid =
        guid_for(&format!("ssx-shell:wflow:input:{}", a.id)).trim_matches(['{', '}']).to_owned();
    let output_uuid =
        guid_for(&format!("ssx-shell:wflow:output:{}", a.id)).trim_matches(['{', '}']).to_owned();
    Ok(WFLOW_TEMPLATE
        .replace("@@PLIST_HEAD@@", PLIST_HEAD)
        .replace("@@MARKER@@", MARKER)
        .replace("@@SCRIPT@@", &script)
        .replace("@@UUID@@", &action_uuid)
        .replace("@@INPUT_UUID@@", &input_uuid)
        .replace("@@OUTPUT_UUID@@", &output_uuid))
}

const WFLOW_TEMPLATE: &str = r#"@@PLIST_HEAD@@<!-- @@MARKER@@: generated by ssx. Edits are overwritten. -->
<plist version="1.0">
<dict>
	<key>AMApplicationBuild</key>
	<string>523</string>
	<key>AMApplicationVersion</key>
	<string>2.10</string>
	<key>AMDocumentVersion</key>
	<string>2</string>
	<key>actions</key>
	<array>
		<dict>
			<key>action</key>
			<dict>
				<key>AMAccepts</key>
				<dict>
					<key>Container</key>
					<string>List</string>
					<key>Optional</key>
					<true/>
					<key>Types</key>
					<array>
						<string>com.apple.cocoa.string</string>
					</array>
				</dict>
				<key>AMActionVersion</key>
				<string>2.0.3</string>
				<key>AMApplication</key>
				<array>
					<string>Automator</string>
				</array>
				<key>AMParameterProperties</key>
				<dict>
					<key>COMMAND_STRING</key>
					<dict/>
					<key>CheckedForUserDefaultShell</key>
					<dict/>
					<key>inputMethod</key>
					<dict/>
					<key>shell</key>
					<dict/>
					<key>source</key>
					<dict/>
				</dict>
				<key>AMProvides</key>
				<dict>
					<key>Container</key>
					<string>List</string>
					<key>Types</key>
					<array>
						<string>com.apple.cocoa.string</string>
					</array>
				</dict>
				<key>ActionBundlePath</key>
				<string>/System/Library/Automator/Run Shell Script.action</string>
				<key>ActionName</key>
				<string>Run Shell Script</string>
				<key>ActionParameters</key>
				<dict>
					<key>COMMAND_STRING</key>
					<string>@@SCRIPT@@</string>
					<key>CheckedForUserDefaultShell</key>
					<true/>
					<key>inputMethod</key>
					<integer>1</integer>
					<key>shell</key>
					<string>/bin/bash</string>
					<key>source</key>
					<string></string>
				</dict>
				<key>BundleIdentifier</key>
				<string>com.apple.RunShellScript</string>
				<key>CFBundleVersion</key>
				<string>2.0.3</string>
				<key>CanShowSelectedItemsWhenRun</key>
				<false/>
				<key>CanShowWhenRun</key>
				<true/>
				<key>Category</key>
				<array>
					<string>AMCategoryUtilities</string>
				</array>
				<key>Class Name</key>
				<string>RunShellScriptAction</string>
				<key>InputUUID</key>
				<string>@@INPUT_UUID@@</string>
				<key>Keywords</key>
				<array>
					<string>Shell</string>
					<string>Script</string>
					<string>Command</string>
					<string>Run</string>
					<string>Unix</string>
				</array>
				<key>OutputUUID</key>
				<string>@@OUTPUT_UUID@@</string>
				<key>UUID</key>
				<string>@@UUID@@</string>
				<key>UnlocalizedApplications</key>
				<array>
					<string>Automator</string>
				</array>
				<key>arguments</key>
				<dict>
					<key>0</key>
					<dict>
						<key>default value</key>
						<integer>0</integer>
						<key>name</key>
						<string>inputMethod</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>0</string>
					</dict>
					<key>1</key>
					<dict>
						<key>default value</key>
						<string></string>
						<key>name</key>
						<string>source</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>1</string>
					</dict>
					<key>2</key>
					<dict>
						<key>default value</key>
						<false/>
						<key>name</key>
						<string>CheckedForUserDefaultShell</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>2</string>
					</dict>
					<key>3</key>
					<dict>
						<key>default value</key>
						<string></string>
						<key>name</key>
						<string>COMMAND_STRING</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>3</string>
					</dict>
					<key>4</key>
					<dict>
						<key>default value</key>
						<string>/bin/sh</string>
						<key>name</key>
						<string>shell</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>4</string>
					</dict>
				</dict>
				<key>isViewVisible</key>
				<integer>1</integer>
				<key>location</key>
				<string>309.000000:305.000000</string>
				<key>nibPath</key>
				<string>/System/Library/Automator/Run Shell Script.action/Contents/Resources/Base.lproj/main.nib</string>
			</dict>
			<key>isViewVisible</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>connectors</key>
	<dict/>
	<key>workflowMetaData</key>
	<dict>
		<key>applicationBundleIDsByPath</key>
		<dict/>
		<key>applicationPaths</key>
		<array/>
		<key>inputTypeIdentifier</key>
		<string>com.apple.Automator.fileSystemObject</string>
		<key>outputTypeIdentifier</key>
		<string>com.apple.Automator.nothing</string>
		<key>presentationMode</key>
		<integer>15</integer>
		<key>processesInput</key>
		<integer>0</integer>
		<key>serviceApplicationBundleID</key>
		<string>com.apple.finder</string>
		<key>serviceApplicationPath</key>
		<string>/System/Library/CoreServices/Finder.app</string>
		<key>serviceInputTypeIdentifier</key>
		<string>com.apple.Automator.fileSystemObject</string>
		<key>serviceOutputTypeIdentifier</key>
		<string>com.apple.Automator.nothing</string>
		<key>serviceProcessesInput</key>
		<integer>0</integer>
		<key>systemImageName</key>
		<string>NSActionTemplate</string>
		<key>useAutomaticInputType</key>
		<integer>0</integer>
		<key>workflowTypeIdentifier</key>
		<string>com.apple.Automator.servicesMenu</string>
	</dict>
</dict>
</plist>
"#;
