//! Generic freedesktop `.desktop` entries: "Open With > Upload with ssx" in every file manager
//! that honours the Desktop Entry / MIME associations specs (PCManFM(-Qt), Thunar, Caja,
//! Nautilus, Dolphin, yazi's `open`, `xdg-open` pickers, ...).
//!
//! The `Exec=` line follows the Desktop Entry spec quoting rules exactly and uses `%F`/`%f`,
//! which the launcher expands to one argv element per file, so names are never re-parsed.
//! `--` precedes them. Entries are *not* `NoDisplay` by default: several launchers hide
//! `NoDisplay` apps from "Open With" as well, which would defeat the purpose; set
//! [`DesktopEntries::hide_from_menus`] to opt in to `NoDisplay=true` anyway.
//!
//! We deliberately do not touch `mimeapps.list`: an "Open With" candidate needs only a matching
//! `MimeType=`, and rewriting the user's default-application choices is not our business.

use std::path::PathBuf;

use crate::action::{Action, FilterKind, IMAGE_MIME_TYPES, VIDEO_MIME_TYPES};
use crate::context::{Context, Platform};
use crate::error::Result;
use crate::fsutil::{MARKER, ManagedFile, files_current, install_files, uninstall_files};
use crate::integration::{Description, Detection, InstallOutcome, Integration, UninstallOutcome};
use crate::quote::{desktop_exec_arg, keyfile_value};

/// MIME types offered for "any file" actions (desktop entries cannot use wildcards).
pub const COMMON_MIME_TYPES: &[&str] = &[
    "application/octet-stream",
    "inode/directory",
    "text/plain",
    "application/pdf",
    "application/zip",
    "application/x-tar",
    "application/gzip",
    "application/json",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "image/png",
    "image/jpeg",
    "image/gif",
    "image/webp",
    "image/bmp",
    "image/svg+xml",
    "video/mp4",
    "video/webm",
    "video/x-matroska",
    "audio/mpeg",
    "audio/ogg",
    "audio/flac",
];

/// Freedesktop desktop entries in `~/.local/share/applications`.
#[derive(Debug, Clone, Copy, Default)]
pub struct DesktopEntries {
    hide_from_menus: bool,
}

impl DesktopEntries {
    /// Visible entries (default).
    pub fn new() -> Self {
        Self::default()
    }

    /// Keep the entries out of application launchers (`NoDisplay=true`). Some file managers
    /// then also omit them from "Open With".
    pub fn hide_from_menus(mut self, hide: bool) -> Self {
        self.hide_from_menus = hide;
        self
    }

    fn dir(ctx: &Context) -> PathBuf {
        ctx.data_home.join("applications")
    }

    fn files(&self, ctx: &Context) -> Result<Vec<ManagedFile>> {
        // GLib checks that the program in `Exec=` exists *before* decoding `%%`, so a literal
        // '%' in the path (correctly written `%%`) makes the whole entry unloadable. Fail
        // loudly instead of installing an entry that silently never appears.
        if ctx.exe_str()?.contains('%') {
            return Err(crate::error::ShellError::InvalidExe {
                path: ctx.ssx_exe.clone(),
                reason: "GLib cannot load desktop entries whose Exec path contains '%'; install ssx to a path without it".into(),
            });
        }
        ctx.actions
            .iter()
            .map(|a| {
                Ok(ManagedFile::new(
                    Self::dir(ctx).join(format!("ssx-{}.desktop", a.id)),
                    self.source(ctx, a)?,
                    0o644,
                ))
            })
            .collect()
    }

    pub(crate) fn source(&self, ctx: &Context, action: &Action) -> Result<String> {
        let exe = desktop_exec_arg(ctx.exe_str()?);
        let args: Vec<String> = action.exec_args.iter().map(|a| desktop_exec_arg(a)).collect();
        let code = if action.multi_select { "%F" } else { "%f" };
        Ok(format!(
            "[Desktop Entry]\n\
             # {MARKER}: generated by ssx. Edits are overwritten; remove via ssx or delete this file.\n\
             Type=Application\n\
             Name={name}\n\
             Comment={comment}\n\
             Exec={exe} {args} -- {code}\n\
             Icon={icon}\n\
             Terminal=false\n\
             StartupNotify=false\n\
             Categories=Utility;\n\
             MimeType={mime}\n\
             {hide}",
            name = keyfile_value(&action.label),
            comment = keyfile_value(&action.description),
            args = args.join(" "),
            icon = action.icon,
            mime = mime_list(action),
            hide = if self.hide_from_menus { "NoDisplay=true\n" } else { "" },
        ))
    }
}

fn mime_list(action: &Action) -> String {
    let list: Vec<&str> = match action.filter.kind {
        FilterKind::Any => COMMON_MIME_TYPES.to_vec(),
        FilterKind::Images => IMAGE_MIME_TYPES.to_vec(),
        FilterKind::Videos => VIDEO_MIME_TYPES.to_vec(),
        FilterKind::Custom => {
            let mut v: Vec<&str> = action.filter.mime_types.iter().map(String::as_str).collect();
            if action.filter.directories {
                v.push("inode/directory");
            }
            if v.is_empty() {
                v.push("application/octet-stream");
            }
            v
        }
    };
    list.iter().map(|m| format!("{m};")).collect()
}

impl Integration for DesktopEntries {
    fn id(&self) -> &'static str {
        "desktop-entry"
    }

    fn name(&self) -> &'static str {
        "Open With (any file manager)"
    }

    fn platform(&self) -> Platform {
        Platform::Linux
    }

    fn detect(&self, _ctx: &Context) -> Detection {
        Detection::found("freedesktop desktop entries work in every Linux file manager")
    }

    fn install(&self, ctx: &Context) -> Result<InstallOutcome> {
        let outcome = install_files(&self.files(ctx)?)?;
        if outcome != InstallOutcome::AlreadyPresent {
            refresh_database(ctx);
        }
        Ok(outcome)
    }

    fn uninstall(&self, ctx: &Context) -> Result<UninstallOutcome> {
        let outcome = uninstall_files(&self.files(ctx)?, ctx)?;
        if outcome == UninstallOutcome::Removed {
            refresh_database(ctx);
        }
        Ok(outcome)
    }

    fn is_installed(&self, ctx: &Context) -> Result<bool> {
        files_current(&self.files(ctx)?)
    }

    fn describe(&self, ctx: &Context) -> Description {
        let paths: Vec<PathBuf> =
            self.files(ctx).map(|f| f.into_iter().map(|f| f.path).collect()).unwrap_or_default();
        Description::paths(
            "desktop-entry",
            "Desktop entries: right-click > Open With > Upload with ssx",
            &paths,
        )
        .note("runs `update-desktop-database` on ~/.local/share/applications when available")
    }
}

/// Best effort: refresh the MIME cache so "Open With" sees the entries without a re-login.
fn refresh_database(ctx: &Context) {
    let dir = DesktopEntries::dir(ctx).display().to_string();
    if let Err(e) = ctx.runner.run("update-desktop-database", &[dir]) {
        tracing::debug!(error = %e, "update-desktop-database not run");
    }
}
