//! Nemo (Cinnamon) actions: `~/.local/share/nemo/actions/ssx-<id>.nemo_action`.
//!
//! Nemo expands `%F` itself and then runs the line through `g_spawn_command_line_async`
//! (`GLib` shell-style word splitting, *no* shell). With `Quote=single` it wraps every path in
//! single quotes and rewrites embedded `'` as `'\''` (checked in `nemo-action.c`), which is an
//! exact encoding for that parser, so any file name round-trips. Without `Quote=` paths are
//! inserted unquoted and names with spaces would split.
//!
//! Nemo matches `Extensions=` as a case-insensitive *suffix* test, so we write `.png`, not
//! `png`; the special value `any` is only honoured as the sole entry.

use std::path::PathBuf;

use crate::action::Action;
use crate::context::{Context, Platform};
use crate::error::Result;
use crate::fsutil::{MARKER, ManagedFile, files_current, install_files, uninstall_files};
use crate::integration::{Description, Detection, InstallOutcome, Integration, UninstallOutcome};
use crate::quote::{keyfile_value, semicolon_list, shell_word_with_field_codes};

/// Nemo integration.
#[derive(Debug, Clone, Copy, Default)]
pub struct Nemo;

impl Nemo {
    fn dir(ctx: &Context) -> PathBuf {
        ctx.data_home.join("nemo").join("actions")
    }

    fn files(ctx: &Context) -> Result<Vec<ManagedFile>> {
        ctx.actions
            .iter()
            .map(|a| {
                Ok(ManagedFile::new(
                    Self::dir(ctx).join(format!("ssx-{}.nemo_action", a.id)),
                    action_source(ctx, a)?,
                    0o644,
                ))
            })
            .collect()
    }
}

impl Integration for Nemo {
    fn id(&self) -> &'static str {
        "nemo"
    }

    fn name(&self) -> &'static str {
        "Nemo (Cinnamon)"
    }

    fn platform(&self) -> Platform {
        Platform::Linux
    }

    fn detect(&self, ctx: &Context) -> Detection {
        if ctx.has_binary("nemo") {
            Detection::found("`nemo` found in PATH")
        } else if ctx.data_home.join("nemo").is_dir() {
            Detection::found("~/.local/share/nemo exists")
        } else {
            Detection::missing("Nemo is not installed")
        }
    }

    fn install(&self, ctx: &Context) -> Result<InstallOutcome> {
        install_files(&Self::files(ctx)?)
    }

    fn uninstall(&self, ctx: &Context) -> Result<UninstallOutcome> {
        uninstall_files(&Self::files(ctx)?, ctx)
    }

    fn is_installed(&self, ctx: &Context) -> Result<bool> {
        files_current(&Self::files(ctx)?)
    }

    fn describe(&self, ctx: &Context) -> Description {
        let paths: Vec<PathBuf> =
            Self::files(ctx).map(|f| f.into_iter().map(|f| f.path).collect()).unwrap_or_default();
        Description::paths("nemo", "Nemo actions (right-click menu)", &paths).note(
            "Nemo watches the actions directory; no restart needed (`nemo -q` if it does not show)",
        )
    }
}

fn extensions_for(action: &Action) -> String {
    if action.filter.is_any() || action.filter.extensions.is_empty() {
        "any;".to_owned()
    } else {
        let dotted: Vec<String> =
            action.filter.extensions.iter().map(|e| format!(".{e}")).collect();
        semicolon_list(dotted.iter().map(String::as_str))
    }
}

/// The `.nemo_action` file for one action.
pub(crate) fn action_source(ctx: &Context, action: &Action) -> Result<String> {
    let exe = shell_word_with_field_codes(ctx.exe_str()?);
    let args: Vec<String> =
        action.exec_args.iter().map(|a| shell_word_with_field_codes(a)).collect();
    let exec = format!("{exe} {} -- %F", args.join(" "));
    Ok(format!(
        "[Nemo Action]\n\
         # {MARKER}: generated by ssx. Edits are overwritten; remove via ssx or delete this file.\n\
         Name={name}\n\
         Comment={comment}\n\
         Exec={exec}\n\
         Icon-Name={icon}\n\
         Selection={selection}\n\
         Extensions={ext}\n\
         Quote=single\n",
        name = keyfile_value(&action.label),
        comment = keyfile_value(&action.description),
        exec = keyfile_value(&exec),
        icon = action.icon,
        selection = if action.multi_select { "notnone" } else { "s" },
        ext = extensions_for(action),
    ))
}
