#!/bin/sh
# ssx-shell-managed: generated by ssx for Nautilus. Edits are overwritten; delete via ssx or remove this file.
# Entry: Edit image with ssx (edit)
SSX='/usr/bin/ssx'

# Nautilus passes the selected local files as arguments, relative to the folder
# being viewed. Rebuild "$@" with absolute paths (the app has another working
# directory) without word-splitting, globbing or evaluating any file name.
n=$#
while [ "$n" -gt 0 ]; do
    f=$1
    shift
    case $f in
        /*) ;;
        *) f=${PWD%/}/$f ;;
    esac
    set -- "$@" "$f"
    n=$((n - 1))
done

# Scripts cannot be filtered by type in Nautilus, so filter here.
n=$#
while [ "$n" -gt 0 ]; do
    f=$1
    shift
    case $f in
        *.[pP][nN][gG]|*.[jJ][pP][gG]|*.[jJ][pP][eE][gG]|*.[jJ][pP][eE]|*.[gG][iI][fF]|*.[wW][eE][bB][pP]|*.[bB][mM][pP]|*.[tT][iI][fF]|*.[tT][iI][fF][fF]|*.[aA][vV][iI][fF]|*.[hH][eE][iI][cC]|*.[hH][eE][iI][fF]) set -- "$@" "$f" ;;
    esac
    n=$((n - 1))
done

[ "$#" -gt 0 ] || exit 0
for f in "$@"; do
    "$SSX" edit -- "$f"
done
