# ssx-shell-managed: generated by ssx for Nautilus. Edits are overwritten; remove via ssx or delete this file.
# Requires nautilus-python (python3-nautilus / nautilus-python). Restart Nautilus: nautilus -q
import subprocess
import sys

import gi

try:
    gi.require_version("Nautilus", "4.0")
except ValueError:
    gi.require_version("Nautilus", "3.0")
from gi.repository import GObject, Nautilus

SSX = "/usr/bin/ssx"

ACTIONS = [
    {
        "id": "upload",
        "label": "Upload with ssx",
        "tip": "Upload the selected files with ssx",
        "args": ["post-file"],
        "multi": True,
        "directories": True,
        "extensions": [],
        "mimes": [],
    },
    {
        "id": "edit",
        "label": "Edit image with ssx",
        "tip": "Open the selected image in the ssx editor",
        "args": ["edit"],
        "multi": False,
        "directories": False,
        "extensions": ["png", "jpg", "jpeg", "jpe", "gif", "webp", "bmp", "tif", "tiff", "avif", "heic", "heif"],
        "mimes": ["image/png", "image/jpeg", "image/gif", "image/webp", "image/bmp", "image/tiff", "image/avif", "image/heif", "image/heic"],
    },
    {
        "id": "upload-video",
        "label": "Upload video with ssx",
        "tip": "Upload the selected video with ssx",
        "args": ["post-video"],
        "multi": False,
        "directories": False,
        "extensions": ["mp4", "mkv", "webm", "mov", "avi", "wmv", "flv", "m4v", "ogv", "mpg", "mpeg"],
        "mimes": ["video/mp4", "video/x-matroska", "video/webm", "video/quicktime", "video/x-msvideo", "video/x-ms-wmv", "video/x-flv", "video/x-m4v", "video/ogg", "video/mpeg"],
    },
]


def _local_paths(files):
    """Absolute paths of the selection, or [] if anything is not a local file."""
    paths = []
    for f in files:
        if f.get_uri_scheme() != "file":
            return []
        location = f.get_location()
        path = location.get_path() if location is not None else None
        if not path:
            return []
        paths.append(path)
    return paths


def _matches(action, f):
    if f.is_directory():
        return action["directories"]
    exts, mimes = action["extensions"], action["mimes"]
    if not exts and not mimes:
        return True
    stem, dot, ext = f.get_name().lower().rpartition(".")
    if exts and dot and stem and ext in exts:
        return True
    return bool(mimes) and f.get_mime_type() in mimes


class SsxMenuProvider(GObject.GObject, Nautilus.MenuProvider):
    def _items(self, files):
        files = list(files)
        paths = _local_paths(files)
        if not files or not paths:
            return []
        items = []
        for action in ACTIONS:
            if not action["multi"] and len(files) != 1:
                continue
            if not all(_matches(action, f) for f in files):
                continue
            item = Nautilus.MenuItem(
                name="SsxShell::" + action["id"],
                label=action["label"],
                tip=action["tip"],
            )
            item.connect("activate", self._on_activate, action, paths)
            items.append(item)
        return items

    def _on_activate(self, _menu, action, paths):
        # An argv list, never a shell string; "--" stops option parsing for names like "-x".
        argv = [SSX] + action["args"] + ["--"] + paths
        try:
            subprocess.Popen(argv, close_fds=True, start_new_session=True)
        except OSError as err:
            print("ssx: cannot start %s: %s" % (SSX, err), file=sys.stderr)

    # Nautilus 43+ (GTK4) calls get_file_items(files); older versions (window, files).
    def get_file_items(self, *args):
        return self._items(args[-1])

    def get_background_items(self, *args):
        return []
