#!/bin/sh
# ssx-shell-managed: generated by ssx for Nautilus. Edits are overwritten; delete via ssx or remove this file.
# Entry: Upload with ssx (upload)
SSX='/usr/bin/ssx'

# Nautilus passes the selected local files as arguments, relative to the folder
# being viewed. Rebuild "$@" with absolute paths (the app has another working
# directory) without word-splitting, globbing or evaluating any file name.
n=$#
while [ "$n" -gt 0 ]; do
    f=$1
    shift
    case $f in
        /*) ;;
        *) f=${PWD%/}/$f ;;
    esac
    set -- "$@" "$f"
    n=$((n - 1))
done

[ "$#" -gt 0 ] || exit 0
exec "$SSX" post-file -- "$@"
