#!/bin/sh
# ssx-shell-managed: generated by ssx for Nautilus. Edits are overwritten; delete via ssx or remove this file.
# Entry: Upload video with ssx (upload-video)
SSX='/usr/bin/ssx'

# Nautilus passes the selected local files as arguments, relative to the folder
# being viewed. Rebuild "$@" with absolute paths (the app has another working
# directory) without word-splitting, globbing or evaluating any file name.
n=$#
while [ "$n" -gt 0 ]; do
    f=$1
    shift
    case $f in
        /*) ;;
        *) f=${PWD%/}/$f ;;
    esac
    set -- "$@" "$f"
    n=$((n - 1))
done

# Scripts cannot be filtered by type in Nautilus, so filter here.
n=$#
while [ "$n" -gt 0 ]; do
    f=$1
    shift
    case $f in
        *.[mM][pP]4|*.[mM][kK][vV]|*.[wW][eE][bB][mM]|*.[mM][oO][vV]|*.[aA][vV][iI]|*.[wW][mM][vV]|*.[fF][lL][vV]|*.[mM]4[vV]|*.[oO][gG][vV]|*.[mM][pP][gG]|*.[mM][pP][eE][gG]) set -- "$@" "$f" ;;
    esac
    n=$((n - 1))
done

[ "$#" -gt 0 ] || exit 0
for f in "$@"; do
    "$SSX" post-video -- "$f"
done
