//! Hyprland: `bind = MODS, key, exec, command` lines in a file we own.
//!
//! The simple, submap-free form. The file is loaded with `source = <path>` from
//! `hyprland.conf`. Modifiers are written `CTRL`, `ALT`, `SHIFT`, `SUPER` separated by
//! spaces; keys are XKB keysym names (Hyprland resolves them case-insensitively).
//!
//! Verification status: this syntax is taken from the Hyprland wiki ("Binds") and
//! `hyprland.conf` conventions; Hyprland could not be run in the development environment,
//! unlike sway, GNOME's `gsettings` and the XDG portal, which were exercised for real.

use std::path::Path;

use crate::{
    chord::{Chord, Modifiers},
    command::{Command, hyprland_exec_arg},
};

use super::{Result, comment_text, validate};

/// The `MODS` field: `CTRL SHIFT`, or empty.
pub fn mods_syntax(chord: &Chord) -> String {
    chord
        .modifiers()
        .iter()
        .map(|m| match m {
            Modifiers::CTRL => "CTRL",
            Modifiers::ALT => "ALT",
            Modifiers::SHIFT => "SHIFT",
            _ => "SUPER",
        })
        .collect::<Vec<_>>()
        .join(" ")
}

/// One `bind` line (no trailing newline).
pub fn bind_line(chord: &Chord, command: &Command) -> String {
    format!(
        "bind = {}, {}, exec, {}",
        mods_syntax(chord),
        chord.key().xkb_name(),
        hyprland_exec_arg(command)
    )
}

/// The complete contents of `ssx.conf`.
pub fn render(bindings: &[(Chord, Command)]) -> Result<String> {
    validate(bindings)?;
    let mut out = String::from(
        "# Generated by ssx. Do not edit: this file is rewritten by `ssx hotkeys install`.\n\
         # Load it from hyprland.conf with the `source` line printed by that command.\n",
    );
    for (chord, cmd) in bindings {
        out.push_str(&format!("\n# {chord}: {}\n", comment_text(&cmd.display_name()).replace('#', "##")));
        out.push_str(&bind_line(chord, cmd));
        out.push('\n');
    }
    Ok(out)
}

/// The line to add to `hyprland.conf` to load `file`.
pub fn source_line(file: &Path) -> String {
    format!("source = {}", file.display())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bindings::tests::fixture;

    #[test]
    fn bind_lines() {
        let c = Command::new("ssx").args(["capture", "region"]);
        assert_eq!(bind_line(&"Ctrl+Shift+S".parse().unwrap(), &c), "bind = CTRL SHIFT, s, exec, ssx capture region");
        assert_eq!(bind_line(&"Print".parse().unwrap(), &c), "bind = , Print, exec, ssx capture region");
        assert_eq!(bind_line(&"Super+Alt+R".parse().unwrap(), &c), "bind = ALT SUPER, r, exec, ssx capture region");
    }

    #[test]
    fn commas_in_arguments_survive_because_exec_takes_the_rest_of_the_line() {
        let c = Command::new("notify-send").arg("a, b, c");
        assert_eq!(
            bind_line(&"Print".parse().unwrap(), &c),
            "bind = , Print, exec, notify-send 'a, b, c'"
        );
    }

    #[test]
    fn render_and_comment_escaping() {
        let text = render(&fixture()).unwrap();
        assert_eq!(text.matches("\nbind = ").count(), 3);
        let c = vec![("Print".parse().unwrap(), Command::new("x").label("say # hi"))];
        assert!(render(&c).unwrap().contains("# Print: say ## hi\n"));
        assert!(render(&[("Print".parse().unwrap(), Command::new(""))]).is_err());
    }

    #[test]
    fn source_line_is_plain() {
        assert_eq!(source_line(Path::new("/h/.config/hypr/ssx.conf")), "source = /h/.config/hypr/ssx.conf");
    }
}
