//! sway: `bindsym` lines in an include file we own.
//!
//! sway has no way for an application to grab keys, so ssx writes
//! `~/.config/sway/config.d/ssx.conf` and the user adds one `include` line to their config
//! (or opts in to [`files::install_main_include`](super::files::install_main_include),
//! which appends a marked, removable block). Modifier spelling is `Ctrl`, `Alt`, `Shift`
//! and `Mod4` for the Super key (sway accepts `Mod4` everywhere, `Super` only in newer
//! versions). Key names are XKB keysyms and were validated against a real sway.

use std::{fmt::Write as _, path::Path};

use crate::{
    chord::{Chord, Modifiers},
    command::{Command, sway_bindsym_exec_arg, sway_exec_arg},
};

use super::{Result, comment_text, validate};

/// The text after `exec` for a *one-shot* sway command (`exec_always`, `swaymsg exec`);
/// see [`crate::command::sway_exec_arg`] for why it looks the way it does.
pub fn exec_arg(command: &Command) -> String {
    sway_exec_arg(command)
}

/// A chord in sway syntax: `Ctrl+Shift+s`, `Mod4+Alt+r`, `Print`.
pub fn chord_syntax(chord: &Chord) -> String {
    chord.join_with(
        "+",
        |m| {
            match m {
                Modifiers::CTRL => "Ctrl",
                Modifiers::ALT => "Alt",
                Modifiers::SHIFT => "Shift",
                _ => "Mod4",
            }
            .to_owned()
        },
        chord.key().xkb_name(),
    )
}

/// One `bindsym` line (no trailing newline).
pub fn bindsym_line(chord: &Chord, command: &Command) -> String {
    format!("bindsym {} exec {}", chord_syntax(chord), sway_bindsym_exec_arg(command))
}

/// The complete contents of `ssx.conf`.
pub fn render(bindings: &[(Chord, Command)]) -> Result<String> {
    validate(bindings)?;
    let mut out = String::from(
        "# Generated by ssx. Do not edit: this file is rewritten by `ssx hotkeys install`.\n\
         # Include it from your sway config with the line printed by that command.\n",
    );
    for (chord, cmd) in bindings {
        let _ = write!(out, "\n# {chord}: {}\n", comment_text(&cmd.display_name()));
        out.push_str(&bindsym_line(chord, cmd));
        out.push('\n');
    }
    Ok(out)
}

/// The line to add to the main config to load `include_file`.
///
/// sway passes the path through `wordexp`, which splits on spaces even inside double
/// quotes (verified: `include "/a b/c"` silently loads nothing), so unusual characters are
/// backslash-escaped instead: `include /home/my\ user/x.conf`.
pub fn include_line(include_file: &Path) -> String {
    let mut out = String::from("include ");
    for c in include_file.display().to_string().chars() {
        if !(c.is_ascii_alphanumeric()
            || matches!(c, '/' | '.' | '_' | '-' | '+' | ':' | '@' | ','))
        {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bindings::tests::fixture;

    #[test]
    fn chord_spelling() {
        assert_eq!(chord_syntax(&"Ctrl+Shift+S".parse().unwrap()), "Ctrl+Shift+s");
        assert_eq!(chord_syntax(&"Super+Alt+R".parse().unwrap()), "Alt+Mod4+r");
        assert_eq!(chord_syntax(&"Print".parse().unwrap()), "Print");
        assert_eq!(
            chord_syntax(&"Super+Ctrl+Alt+Shift+Enter".parse().unwrap()),
            "Ctrl+Alt+Shift+Mod4+Return"
        );
    }

    #[test]
    fn bindsym_lines_double_quote_only_what_needs_it() {
        let c = Command::new("ssx").args(["capture", "region"]);
        assert_eq!(
            bindsym_line(&"Print".parse().unwrap(), &c),
            "bindsym Print exec ssx capture region"
        );
        assert_eq!(exec_arg(&c), "ssx capture region");
        let spaced = Command::new("ssx").args(["a b", "c,d", "e;f", ""]);
        assert_eq!(exec_arg(&spaced), "ssx \"a b\" \"c,d\" \"e;f\" \"\"");
    }

    #[test]
    fn bindsym_escapes_one_level_deeper_than_one_shot_commands() {
        // Word: a"b$c\d`e   (quote, dollar, backslash, backtick)
        let c = Command::new("x").arg("a\"b$c\\d`e");
        // One-shot: shell-level escapes only.
        assert_eq!(exec_arg(&c), "x \"a\\\"b\\$c\\\\d\\`e\"");
        // bindsym: `\\` and `\"` are escaped once more (sway unescapes them when storing the
        // command); `\$` and `` \` `` are not.
        assert_eq!(
            bindsym_line(&"Print".parse().unwrap(), &c),
            "bindsym Print exec x \"a\\\\\\\"b\\$c\\\\\\\\d\\`e\""
        );
    }

    #[test]
    fn render_lists_every_binding_and_rejects_bad_lists() {
        let text = render(&fixture()).unwrap();
        assert_eq!(text.matches("bindsym ").count(), 3);
        assert!(text.contains("# Ctrl+Shift+S: Capture region\n"));
        assert!(render(&[("Print".parse().unwrap(), Command::new("a\nb"))]).is_err());
        assert!(render(&[]).unwrap().lines().all(|l| l.starts_with('#')));
    }

    #[test]
    fn include_line_quotes_only_when_needed() {
        assert_eq!(
            include_line(Path::new("/home/u/.config/sway/config.d/ssx.conf")),
            "include /home/u/.config/sway/config.d/ssx.conf"
        );
        assert_eq!(
            include_line(Path::new("/home/my user/x.conf")),
            "include /home/my\\ user/x.conf"
        );
        assert_eq!(include_line(Path::new("/h/a\"b$c")), "include /h/a\\\"b\\$c");
    }
}
